site_name: Loopring Documentation
theme: readthedocs
strict: true
repo_url: https://github.com/Loopring/documents
site_description: Loopring - Decentralized Token Exchange Protocol
pages:
    - About: index.md
    - English:
        - Overview: English/overview.md
        - LRC Token: English/token.md
        - 'Protocol': English/projects/protocol.md
        - 'Relays': English/projects/relay.md
        - 'Wallets': English/projects/wallet.md
        - 'Tokenization Services': English/projects/tokenization.md
        - Contribution: English/contribution.md
    - 日语:
        - Overview: Japanese/overview.md
        - LRC Token: Japanese/token.md
        - 'Protocol': Japanese/projects/protocol.md
        - 'Relays': Japanese/projects/relay.md
        - '財布': Japanese/projects/wallet.md
        - 'トークン化サービス': Japanese/projects/tokenization.md
        - 貢献: Japanese/contribution.md
    # - Portuguese:
    #     - Overview: Portuguese/overview.md
    #     - LRC Token: Portuguese/token.md
    #     - 'Protocol': Portuguese/projects/protocol.md
    #     - 'Relays': Portuguese/projects/relay.md
    #     - 'Ring Miners': Portuguese/projects/ringminer.md
    #     - 'Wallets': Portuguese/projects/wallet.md
    #     - 'Tokenization Services': Portuguese/projects/tokenization.md
    #     - Contribution: Portuguese/contribution.md

    # - 中文:
    #     - 概览: Chinese/overview.md
    #     - LRC代币: Chinese/token.md
        # - 'Protocol': Chinese/projects/protocol.md
        # - 'Relays': Chinese/projects/relay.md
        # - 'Ring Miners': Chinese/projects/ringminer.md
        # - 'Wallets': Chinese/projects/wallet.md
        # - 'Tokenization Services': Chinese/projects/tokenization.md
        # - 社区贡献: Chinese/contribution.md